# Generated by Django 5.1.6 on 2025-03-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
                ('phone', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='officer/images')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
