# Generated by Django 5.1.6 on 2025-03-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0003_role_advocaterole'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocaterole',
            name='session',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
