# Generated by Django 5.1.6 on 2025-03-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0004_advocaterole_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='aibe_number',
            field=models.CharField(default=12345, max_length=50),
            preserve_default=False,
        ),
    ]
