# Generated by Django 5.1.6 on 2025-03-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0005_advocate_aibe_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='aibe_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='advocates/profile_images/'),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='registration_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='zip',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
