# Generated by Django 5.1.6 on 2025-05-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0006_alter_advocate_aibe_number_alter_advocate_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='practicing_since',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
