# Generated by Django 5.1.6 on 2025-03-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.ImageField(default=1, upload_to='services/'),
            preserve_default=False,
        ),
    ]
