# Generated by Django 5.1.6 on 2025-03-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_incomecategory_rename_category_expensecategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomecategory',
            options={'verbose_name_plural': 'Income Categories'},
        ),
    ]
